
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem;DB_CLOSE_DELAY=2;AUTO_SERVER=TRUE #DB_CLOSE_ON_EXIT=false
#    username: sa
#    password:
#    driverClassName: org.h2.Driver